### ISSUE TITLE
Rolling window for profile and lookup dataset

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-platform.en#23]
Issue in ./help/getting-started/estimate-usage.md

I believe there is an inconsistency in this sentence:

> Data retention is based on event dataset timestamps and applies to event datasets only. No rolling data window setting exists for profile or lookup datasets, since there are no applicable timestamps. However, if your connection includes any profile or lookup datasets (besides one or more event datasets), that data will be retained for the same time period.

What does it means: "data will be retained for the same time period"? How the time period is calculated?

**Comment by MicaPete** [comment]
The updated sentence reads: "If your connection includes any profile or lookup datasets, since they are joined with event datasets, the data is retained in CJA based on your data retention settings on the event dataset timestamps."

https://experienceleague.adobe.com/docs/analytics-platform/using/cja-overview/estimate-usage.html
